export const USER_SIGN_UP_REQUEST =  "USER_SIGN_UP_REQUEST"
export const USER_SIGN_UP_SUCCESS =  "USER_SIGN_UP_SUCCESS"
export const USER_SIGN_UP_FAIL =  "USER_SIGN_UP_FAIL"
export const USER_SIGN_UP_RESET =  "USER_SIGN_UP_RESET"

export const USER_SIGN_IN_REQUEST =  "USER_SIGN_IN_REQUEST"
export const USER_SIGN_IN_SUCCESS =  "USER_SIGN_IN_SUCCESS"
export const USER_SIGN_IN_FAIL =  "USER_SIGN_IN_FAIL"
export const USER_SIGN_IN_RESET =  "USER_SIGN_IN_RESET"
export const USER_LOGOUT = "USER_LOGOUT"

export const ADMIN_SIGN_UP_REQUEST =  "ADMIN_SIGN_UP_REQUEST"
export const ADMIN_SIGN_UP_SUCCESS =  "ADMIN_SIGN_UP_SUCCESS"
export const ADMIN_SIGN_UP_FAIL =  "ADMIN_SIGN_UP_FAIL"
export const ADMIN_SIGN_UP_RESET =  "ADMIN_SIGN_UP_RESET"

export const ADMIN_SIGN_IN_REQUEST =  "ADMIN_SIGN_IN_REQUEST"
export const ADMIN_SIGN_IN_SUCCESS =  "ADMIN_SIGN_IN_SUCCESS"
export const ADMIN_SIGN_IN_FAIL =  "ADMIN_SIGN_IN_FAIL"
export const ADMIN_SIGN_IN_RESET =  "ADMIN_SIGN_IN_RESET"
export const ADMIN_LOGOUT = "ADMIN_LOGOUT"

export const GET_ALL_USERS_REQUEST =  "GET_ALL_USERS_REQUEST"
export const GET_ALL_USERS_SUCCESS =  "GET_ALL_USERS_SUCCESS"
export const GET_ALL_USERS_FAIL =  "GET_ALL_USERS_FAIL"
export const GET_ALL_USERS_RESET =  "GET_ALL_USERS_RESET"

export const USER_UPDATE_REQUEST =  "USER_UPDATE_REQUEST"
export const USER_UPDATE_SUCCESS =  "USER_UPDATE_SUCCESS"
export const USER_UPDATE_FAIL =  "USER_UPDATE_FAIL"
export const USER_UPDATE_RESET =  "USER_UPDATE_RESET"

export const GET_SINGLE_USER_REQUEST =  "GET_SINGLE_USER_REQUEST"
export const GET_SINGLE_USER_SUCCESS =  "GET_SINGLE_USER_SUCCESS"
export const GET_SINGLE_USER_FAIL =  "GET_SINGLE_USER_FAIL"

export const DELETE_SINGLE_USER_REQUEST =  "DELETE_SINGLE_USER_REQUEST"
export const DELETE_SINGLE_USER_SUCCESS =  "DELETE_SINGLE_USER_SUCCESS"
export const DELETE_SINGLE_USER_FAIL =  "DELETE_SINGLE_USER_FAIL"

export const GET_ALL_TOOLS_REQUEST =  "GET_ALL_TOOLS_REQUEST"
export const GET_ALL_TOOLS_SUCCESS =  "GET_ALL_TOOLS_SUCCESS"
export const GET_ALL_TOOLS_FAIL =  "GET_ALL_TOOLS_FAIL"
export const GET_ALL_TOOLS_RESET =  "GET_ALL_TOOLS_RESET"

export const GET_AVAILABLE_TOOLS_REQUEST =  "GET_AVAILABLE_TOOLS_REQUEST"
export const GET_AVAILABLE_TOOLS_SUCCESS =  "GET_AVAILABLE_TOOLS_SUCCESS"
export const GET_AVAILABLE_TOOLS_FAIL =  "GET_AVAILABLE_TOOLS_FAIL"
export const GET_AVAILABLE_TOOLS_RESET =  "GET_AVAILABLE_TOOLS_RESET"
